name: inception

services:
  nginx:
    container_name: nginx
    image: nginx:inception
    init: true
    restart: on-failure
    build:
      context: requirements/nginx
    networks:
      - inception_network
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    
  wordpress:
    container_name: wordpress
    image: wordpress:inception
    init: true
    restart: on-failure
    build:
      context: requirements/wordpress
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:inception
    init: true
    restart: on-failure
    build:
      context: requirements/mariadb
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql              
    
networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  mariadb_data:
    name: "mariadb_data"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUME_DATA}/mariadb
  wordpress_data:
    name: "wordpress_data"
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUME_DATA}/wordpress
